language: node_js
node_js:
- '6'
deploy:
  provider: heroku
  api_key:
    secure: E8fDL28rwYZyTSzWMFwb9NGww/4YxivsOPAMRxKIvvPNE4kEPu5x+1BsT9eHe8n2Ex/dgnnkJAsogkjJnsK0lJPdtzrVlLYAVDHQGtD/tlbnBLzbrNKukouzZv17Rb4EKquaf8MvVZUOsB3u22arG3EEBooE6BQU0MC8SPNhu+D5SdoMhrtfaPi4zrRxcxU3JRPt2bJW6XshLLdVo1zML+WGHIBrPNyAYpihhpHz9JV9bKTj7iZWc4UEYCIjVZNWp1NB3iDh6dYaedxugCEzjmO9HqLqVpdpFJkaC7foIys1G6AdT6PVfgnKI1bh0uhFYewtzy2mTPvlbIOZ6tDwB4MwulThaCNdfn9BFMOE+8LmnHzoAbgpzZiaDzmHbLlNAHZP9FRvTYGq3s9Dw3aHkm53gu+u8edX5hmxvARGYW4SMllwR8E6a3Iq+kzzT+vMu4FJuk1oO4NvMNja9rTEeM+xLURvLMgtkIKFCureAwfKRlIDDk1kQpTYQoWkk9ldt1wT7d9ctIpXHPWGe1xJ8pcMP52Vi6lMuRLQytpRBZnWXcXXLtjrINNPc95fMY6V+l3kf9Cg9KwAHF/lM9i6FxpQmzn+oUz8gMWukDWtOX5SdTIgYph96hNwSMpECrudauIpajupXSnT4aGxmTnCIGCy6remWxPfKuEwQqmvV9I=
  app: samplr-api
  on:
    repo: chenh1/samplr-api
