language: node_js
node_js:
- '7'
- '6'
deploy:
  provider: heroku
  api_key:
    secure: B4Ww0Z7OUHOJ7LQ5rvdvt2qlXTmOVI9Dc5yGRmx+RzBOL/17rmlXfc6Nk7ZVyLaQ3xUEdoU9TFGXxOhtetpryseHcevBAO5IVvB7s+QZKlmlp4A7x6oR+VVYqPFiB0FmGkN5CGcXf9gvOw9DGpRSq+i0sINFGWpQstx/LrL86GdXJ99n1LxFVWhk6D2s44Ho6tZfrvqvDVANh/BkL9Rsi9vdl4YyMFOxtavkrO4iwd8TcjdXIKAJqMsgdmEg5Hvp4Vwit0WNRPw6okIuXMC3HygLE0NpCRXIosACCiXQXiiA1aPOo2/WwoLFl8VkrlzyWNCpQgCnF9n7v4o9eMwf/cnKhwHksqxndRROoPxY6+2QkolUcLM0CjVQWQVUBI0EUDJVZu3jcHOe78yIvxesNgvryATX2hj+ASUyYUpaT8FISMsIsJRDiuhjoiv1y2pcO4+yBgrpUh7nnb2H2wA2Q3hWBVP+2oYV3hsHNW02YkA1gutF25ctpIeajUWYBKSndjrdpbu2KOOV6U9apgaMxwSr3+m4L2uNC4utapMx1Meu63+x7kaHpZHxWJMKpVR5RmivpsRrWRG6SLdiKagd/VbIJXWaeYxsRmI65ReW5y1dV0fJMg1PXYJKSlRtboI0rIw2S/zwjbZ69w9HbTbORZ6FbSooJPfkBF31W2He5ms=
  app: desolate-peak-60507
  on:
    repo: chenh1/samplr-api
