language: node_js
node_js:
- '6'
deploy:
  provider: heroku
  api_key:
    secure: FOAYtS/0Psb+FeVJ7wZ+PqZFeJ4mGxNJH2qZMh46l05RjxmRv+QoRedWQ/LTMZpr9/e/QAlKZ11mjr248qWqouhiWqVky65uxDaF7LNl1poZxpiVh1Z3pn26eDcSIt9BjwhIox7SGpTZQ+J6hSRBEJA5IykJgcIydTzOiQT/n7LYel4UaTYTVpkC8l+KHvyUUgUbf+FQICwU7EZHjycR0g27kVZDqBPtfKbtM/tzcRDEN9fVRxd502Lb0HonQOTBOiDnipLg+ksHMD9lTDKmG3LCDgqnfFaXYtBzJNyNv5zET1+ObU5GVPQp7cCDYAqyv7zgG3qy7ZlcBFjl9enxamxj0lm5RowlcPvCAcCp+vy48+9A+QgNJVkFpt0Q+olRbzbs8zFqrSjea1cWwpC4/Q8Y4LM8RPZRXBiuQq4wEP4UM9RMtefNy7IMiduvv5/QDujwyusIlO7HSZivisTBofnYBFP6bJWsum2te+5l1oVKbuRjAx/PAbKpkGpVX+AR1N80N/tIWyMjlysTDJJ+Dp3DCaXsGRl3BfyvqrUUztjmHkrM32J5wro+hXH5WkiCaSLKvJaRh76h66wuTbwRRv/2TeVyicQuxsC4VdRniwCN187/nYpCmUa89KDlYCtcINNoemmezale7YospfkEIMvG3YrvxSMyAJkaLrPxaSw=
  app: desolate-peak-60507
  on:
    repo: chenh1/samplr-api
